// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4qJ_Ljw2fDrNsTd808TkgPRGLBoBiazU',
    appId: '1:291088369525:web:2c90a366460f1e1b75753c',
    messagingSenderId: '291088369525',
    projectId: 'stdycrd',
    authDomain: 'stdycrd.firebaseapp.com',
    storageBucket: 'stdycrd.appspot.com',
    measurementId: 'G-9Z0LF5X8XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdaSMbwV2Qq3XwkVENNwzQd_26Bt9oa4',
    appId: '1:291088369525:android:0687a973b09397c575753c',
    messagingSenderId: '291088369525',
    projectId: 'stdycrd',
    storageBucket: 'stdycrd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw_9SGVPbnv8UtNYe4u51fY7aRBBIyNoY',
    appId: '1:291088369525:ios:19bc321ea41bdf5475753c',
    messagingSenderId: '291088369525',
    projectId: 'stdycrd',
    storageBucket: 'stdycrd.appspot.com',
    androidClientId: '291088369525-7l4br3inna2n9e9kjki6ddncsv0hprdr.apps.googleusercontent.com',
    iosClientId: '291088369525-go75ut12j3927cdtdk2c0nk85s12t6td.apps.googleusercontent.com',
    iosBundleId: 'com.jjunguri.snapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw_9SGVPbnv8UtNYe4u51fY7aRBBIyNoY',
    appId: '1:291088369525:ios:ace8960c152fc8a275753c',
    messagingSenderId: '291088369525',
    projectId: 'stdycrd',
    storageBucket: 'stdycrd.appspot.com',
    androidClientId: '291088369525-7l4br3inna2n9e9kjki6ddncsv0hprdr.apps.googleusercontent.com',
    iosClientId: '291088369525-0jfvm4qra8692ufn7qqob7rnta1amtt3.apps.googleusercontent.com',
    iosBundleId: 'com.jjunguri.snapy.RunnerTests',
  );
}
